export enum Actions {
    INITIALZE,
    USER_LOGIN,
    USER_REGISTER,
    SEARCH_REQUEST,
    SEARCH_PROCESS,
    SEARCH_RESULT,
    ITEM_FAVORITE,
    ITEM_UNDO_FAVORITE,
    ITEM_PUBLISH,
    ITEM_COMMENT
}
